server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/user-service/**

        - id: subscription-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/subscription-service/**