server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/user-service/**
        - id: subscription-service
          uri: http://subscription-service:8082
          predicates:
            - Path=/api/subscription-service/**
        - id: battery-service
          uri: http://battery-service:8083
          predicates:
            - Path=/api/battery-service/**
        - id: feedback-service
          uri: http://feedback-service:8086
          predicates:
            - Path=/api/feedback-service/**
        - id: station-service
          uri: http://station-service:8084
          predicates:
            - Path=/api/station-service/**
        - id: transaction-service
          uri: http://transaction-service:8085
          predicates:
            - Path=/api/transaction-service/**
        - id: vehicle-service
          uri: http://vehicle-service:8088
          predicates:
            - Path=/api/vehicle-service/**