spring:
  application:
    name: vehicle-service
  datasource:
    url: jdbc:mysql://mysql_vehicle:3306/vehicle_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8088